__all__ = ["PUBLIC_CLASS_METHODS"]

# Lists the names of all public methods and properties for listed classes. If a class is listed here, the set of public attributes on the class and any instances is based on this data, instead of the method and property lists returned by the Objective-C runtime.
# Note that these name lists only affect which names are listed by the dir function on objc.ID instances. Names not listed here are not made inaccessible, they can still be accessed as usual (directly on the object, via the methods and properties mappings, or via msg_send). As such, these name lists may be changed freely without the risk of breaking any existing scripts.
# These name lists are additive - the full instance name list for a class is that of all classes in the inheritance chain combined. For example, NSString extends NSObject, so its set of public instance attributes contains the name "isKindOfClass:", even though this name is not listed for NSString.
# If a class is not listed here, all names not containing an underscore are assumed to be public. If a class is not listed here, but its superclass is, then only names declared in "unlisted" classes are added automatically to the name list - any inherited names are not added automatically, their visibility is controlled by the name list for the respective superclass. For example, NSObject declares a "retain" method, but this name is not listed as public. For an unlisted class XYExampleClass, its full instance name list does not include "retain".

# Format details:
# PUBLIC_CLASS_METHODS is a mapping. The keys are the class names, the values are 2-tuples, containing collections of the public names on the class and the instances respectively.
# In Python syntax:
# class_attr_names, instance_attr_names = PUBLIC_CLASS_METHODS[clsname]
# NOTE: When listing properties, only list the property name. Do not list the getters and setters separately, as property getters and setters are hidden in dir lists automatically.

PUBLIC_CLASS_METHODS = {
	#--- NSArray
	"NSArray": ([
		"array",
		"arrayWithArray:",
		"arrayWithContentsOfFile:",
		"arrayWithContentsOfURL:",
		"arrayWithObject:",
		"arrayWithObjects:",
		"arrayWithObjects:count:",
	], [
		# Usable methods
		"addObserver:forKeyPath:options:context:",
		"addObserver:toObjectsAtIndexes:forKeyPath:options:context:",
		"arrayByAddingObject:",
		"arrayByAddingObjectsFromArray:",
		"componentsJoinedByString:",
		"containsObject:",
		"count",
		"countByEnumeratingWithState:objects:count:",
		"descriptionWithLocale:",
		"descriptionWithLocale:indent:",
		"encodeWithCoder:",
		"enumerateObjectsAtIndexes:options:usingBlock:",
		"enumerateObjectsUsingBlock:",
		"enumerateObjectsWithOptions:usingBlock:",
		"filteredArrayUsingPredicate:",
		"firstObject",
		"firstObjectCommonWithArray:",
		"getObjects:range:",
		"indexOfObject:",
		"indexOfObject:inRange:",
		"indexOfObject:inSortedRange:options:usingComparator:",
		"indexOfObjectAtIndexes:options:passingTest:",
		"indexOfObjectIdenticalTo:",
		"indexOfObjectIdenticalTo:inRange:",
		"indexOfObjectPassingTest:",
		"indexOfObjectWithOptions:passingTest:",
		"indexesOfObjectsAtIndexes:options:passingTest:",
		"indexesOfObjectsPassingTest:",
		"indexesOfObjectsWithOptions:passingTest:",
		"initWithArray:",
		"initWithArray:copyItems:",
		"initWithCoder:",
		"initWithContentsOfFile:",
		"initWithContentsOfURL:",
		"initWithObjects:",
		"initWithObjects:count:",
		"isEqualToArray:",
		"lastObject",
		"makeObjectsPerformSelector:",
		"makeObjectsPerformSelector:withObject:",
		"objectAtIndex:",
		"objectAtIndexedSubscript:",
		"objectEnumerator",
		"objectsAtIndexes:",
		"pathsMatchingExtensions:",
		"removeObserver:forKeyPath:",
		"removeObserver:forKeyPath:context:",
		"removeObserver:fromObjectsAtIndexes:forKeyPath:",
		"removeObserver:fromObjectsAtIndexes:forKeyPath:context:",
		"reverseObjectEnumerator",
		"setValue:forKey:",
		"shuffledArray",
		"shuffledArrayWithRandomSource:",
		"sortedArrayHint",
		"sortedArrayUsingComparator:",
		"sortedArrayUsingDescriptors:",
		"sortedArrayUsingFunction:context:",
		"sortedArrayUsingFunction:context:hint:",
		"sortedArrayUsingSelector:",
		"sortedArrayWithOptions:usingComparator:",
		"subarrayWithRange:",
		"valueForKey:",
		"writeToFile:atomically:",
		"writeToURL:atomically:",
		
		# Deprecated methods
		##"getObjects:",
	]),
	
	#--- NSCountedSet
	"NSCountedSet": ([], [
		"countForObject:",
	]),
	
	#--- NSData
	"NSData": ([
		# Usable methods
		"data",
		"dataWithBytes:length:",
		"dataWithBytesNoCopy:length:",
		"dataWithBytesNoCopy:length:freeWhenDone:",
		"dataWithContentsOfFile:",
		"dataWithContentsOfFile:options:error:",
		"dataWithContentsOfURL:",
		"dataWithContentsOfURL:options:error:",
		"dataWithData:",
		
		# Deprecated methods
		##"dataWithContentsOfMappedFile:",
	], [
		# Usable methods
		"base64EncodedDataWithOptions:",
		"base64EncodedStringWithOptions:",
		"bytes",
		"description",
		"encodeWithCoder:",
		"enumerateByteRangesUsingBlock:",
		"getBytes:length:",
		"getBytes:range:",
		"initWithBase64EncodedData:options:",
		"initWithBase64EncodedString:options:",
		"initWithBytes:length:",
		"initWithBytesNoCopy:length:",
		"initWithBytesNoCopy:length:deallocator:",
		"initWithBytesNoCopy:length:freeWhenDone:",
		"initWithCoder:",
		"initWithContentsOfFile:",
		"initWithContentsOfFile:options:error:",
		"initWithContentsOfURL:",
		"initWithContentsOfURL:options:error:",
		"initWithData:",
		"isEqualToData:",
		"length",
		"rangeOfData:options:range:",
		"subdataWithRange:",
		"writeToFile:atomically:",
		"writeToFile:options:error:",
		"writeToURL:atomically:",
		"writeToURL:options:error:",
		
		# Deprecated methods
		##"base64Encoding",
		##"getBytes:",
		##"initWithBase64Encoding:",
		##"initWithContentsOfMappedFile:",
	]),
	
	#--- NSDictionary
	"NSDictionary": ([
		# Usable methods
		"dictionary",
		"dictionaryWithContentsOfFile:",
		"dictionaryWithContentsOfURL:",
		"dictionaryWithDictionary:",
		"dictionaryWithObject:forKey:",
		"dictionaryWithObjects:forKeys:",
		"dictionaryWithObjects:forKeys:count:",
		"dictionaryWithObjectsAndKeys:",
		"sharedKeySetForKeys:",
		
		# Deprecated methods
	], [
		# Usable methods
		"allKeys",
		"allKeysForObject:",
		"allValues",
		"count",
		"countByEnumeratingWithState:objects:count:",
		"descriptionInStringsFileFormat",
		"descriptionWithLocale:",
		"descriptionWithLocale:indent:",
		"encodeWithCoder:",
		"enumerateKeysAndObjectsUsingBlock:",
		"enumerateKeysAndObjectsWithOptions:usingBlock:",
		"getObjects:andKeys:count:",
		"initWithCoder:",
		"initWithContentsOfFile:",
		"initWithContentsOfURL:",
		"initWithDictionary:",
		"initWithDictionary:copyItems:",
		"initWithObjects:forKeys:",
		"initWithObjects:forKeys:count:",
		"initWithObjectsAndKeys:",
		"isEqualToDictionary:",
		"keyEnumerator",
		"keysOfEntriesPassingTest:",
		"keysOfEntriesWithOptions:passingTest:",
		"keysSortedByValueUsingComparator:",
		"keysSortedByValueUsingSelector:",
		"keysSortedByValueWithOptions:usingComparator:",
		"objectEnumerator",
		"objectForKey:",
		"objectForKeyedSubscript:",
		"objectsForKeys:notFoundMarker:",
		"valueForKey:",
		"writeToFile:atomically:",
		"writeToURL:atomically:",
		
		# File metadata convenience methods
		##"fileCreationDate",
		##"fileExtensionHidden",
		##"fileGroupOwnerAccountID",
		##"fileGroupOwnerAccountName",
		##"fileHFSCreatorCode",
		##"fileHFSTypeCode",
		##"fileIsAppendOnly",
		##"fileIsImmutable",
		##"fileModificationDate",
		##"fileOwnerAccountID",
		##"fileOwnerAccountName",
		##"filePosixPermissions",
		##"fileSize",
		##"fileSystemFileNumber",
		##"fileSystemNumber",
		##"fileType",
		
		# Deprecated methods
		##"getObjects:andKeys:",
	]),
	
	#--- NSEnumerator
	"NSEnumerator": ([], [
		"allObjects",
		"countByEnumeratingWithState:objects:count:",
		"nextObject",
	]),
	
	#--- NSError
	"NSError": ([
		"errorWithDomain:code:userInfo:",
		"setUserInfoValueProviderForDomain:provider:",
		"userInfoValueProviderForDomain:",
	], [
		"code",
		"domain",
		"helpAnchor",
		"localizedDescription",
		"localizedFailureReason",
		"localizedRecoveryOptions",
		"localizedRecoverySuggestion",
		"initWithDomain:code:userInfo:",
		"recoveryAttempter",
		"userInfo",
	]),
	
	#--- NSMutableArray
	"NSMutableArray": ([
		"arrayWithCapacity:",
		"arrayWithContentsOfFile:",
		"arrayWithContentsOfURL:",
	], [
		# Usable methods
		"addObject:",
		"addObjectsFromArray:",
		"exchangeObjectAtIndex:withObjectAtIndex:",
		"filterUsingPredicate:",
		"initWithCapacity:",
		"initWithContentsOfFile:",
		"initWithContentsOfURL:",
		"insertObject:atIndex:",
		"insertObjects:atIndexes:",
		"removeAllObjects",
		"removeLastObject",
		"removeObject:",
		"removeObject:inRange:",
		"removeObjectAtIndex:",
		"removeObjectIdenticalTo:",
		"removeObjectIdenticalTo:inRange:",
		"removeObjectsAtIndexes:",
		"removeObjectsInArray:",
		"removeObjectsInRange:",
		"replaceObjectAtIndex:withObject:",
		"replaceObjectsAtIndexes:withObjects:",
		"replaceObjectsInRange:withObjectsFromArray:",
		"replaceObjectsInRange:withObjectsFromArray:range:",
		"setArray:",
		"setObject:atIndexedSubscript:",
		"sortUsingComparator:",
		"sortUsingDescriptors:",
		"sortUsingFunction:context:",
		"sortUsingSelector:",
		"sortWithOptions:usingComparator:",
		
		# Deprecated methods
		##"removeObjectsFromIndices:numIndices:",
	]),
	
	#--- NSMutableData
	"NSMutableData": ([
		"dataWithCapacity:",
		"dataWithLength:",
	], [
		"appendBytes:length:",
		"appendData:",
		"increaseLengthBy:",
		"initWithCapacity:",
		"initWithLength:",
		"length",
		"mutableBytes",
		"replaceBytesInRange:withBytes:",
		"replaceBytesInRange:withBytes:length:",
		"resetBytesInRange:",
		"setData:",
	]),
	
	#--- NSMutableDictionary
	"NSMutableDictionary": ([
		"dictionaryWithCapacity:",
		"dictionaryWithSharedKeySet:",
	], [
		"addEntriesFromDictionary:",
		"initWithCapacity:",
		"removeAllObjects",
		"removeObjectForKey:",
		"removeObjectsForKeys:",
		"setObject:forKey:",
		"setObject:forKeyedSubscript:",
		"setDictionary:",
		"setValue:forKey:",
	]),
	
	#--- NSMutableSet
	"NSMutableSet": ([
		"setWithCapacity:",
	], [
		"addObject:",
		"addObjectsFromArray:",
		"filterUsingPredicate:",
		"initWithCapacity:",
		"intersectSet:",
		"minusSet:",
		"removeAllObjects",
		"removeObject:",
		"setSet:",
		"unionSet:",
	]),
	
	#--- NSMutableString
	"NSMutableString": ([
		"stringWithCapacity:",
	], [
		"appendString:",
		"appendFormat:",
		"applyTransform:reverse:range:updatedRange:",
		"deleteCharactersInRange:",
		"initWithCapacity:",
		"insertString:atIndex:",
		"replaceCharactersInRange:withString:",
		"replaceOccurrencesOfString:withString:options:range:",
		"setString:",
	]),
	
	#--- NSNull
	"NSNull": ([
		"null",
	], [
		"encodeWithCoder:",
		"initWithCoder:",
	]),
	
	#--- NSNumber
	"NSNumber": ([
		"numberWithBool:",
		"numberWithChar:",
		"numberWithDouble:",
		"numberWithFloat:",
		"numberWithInt:",
		"numberWithInteger:",
		"numberWithLong:",
		"numberWithLongLong:",
		"numberWithShort:",
		"numberWithUnsignedChar:",
		"numberWithUnsignedInt:",
		"numberWithUnsignedInteger:",
		"numberWithUnsignedLong:",
		"numberWithUnsignedLongLong:",
		"numberWithUnsignedShort:",
	], [
		"boolValue",
		"charValue",
		"compare:",
		"decimalValue",
		"descriptionWithLocale:",
		"doubleValue",
		"encodeWithCoder:",
		"floatValue",
		"initWithBool:",
		"initWithChar:",
		"initWithDouble:",
		"initWithFloat:",
		"initWithInt:",
		"initWithInteger:",
		"initWithLong:",
		"initWithLongLong:",
		"initWithShort:",
		"initWithUnsignedChar:",
		"initWithUnsignedInt:",
		"initWithUnsignedInteger:",
		"initWithUnsignedLong:",
		"initWithUnsignedLongLong:",
		"initWithUnsignedShort:",
		"intValue",
		"integerValue",
		"isEqualToNumber:",
		"longLongValue",
		"longValue",
		"shortValue",
		"stringValue",
		"unsignedCharValue",
		"unsignedIntegerValue",
		"unsignedIntValue",
		"unsignedLongLongValue",
		"unsignedLongValue",
		"unsignedShortValue",
	]),
	
	#--- NSObject
	"NSObject": ([
		# Usable methods
		"alloc",
		"debugDescription",
		"description",
		"hash",
		"instanceMethodForSelector:",
		"instanceMethodSignatureForSelector:",
		"new",
		
		# Methods for which objc provides better interfaces
		##"class", # Not necessary
		##"conformsToProtocol:", # issubclass(cls, proto)
		##"instancesRespondToSelector:", # cls.instances_respond_to(sel)
		##"isSubclassOfClass:", # issubclass(cls, supercls)
		##"superclass", # cls.superclass
		##"version", # cls.version
		
		# Methods that aren't really useful
		##"cancelPreviousPerformRequestsWithTarget:",
		##"cancelPreviousPerformRequestsWithTarget:selector:object:",
		
		# Methods that shouldn't be called directly
		##"classFallbacksForKeyedArchiver",
		##"classForKeyedUnarchiver",
		##"initialize",
		##"load",
		##"resolveClassMethod:",
		##"resolveInstanceMethod:",
		##"setVersion:",
		
		# Deprecated methods
		##"allocWithZone:",
		##"copyWithZone:",
		##"mutableCopyWithZone:",
		##"poseAsClass:",
	], [
		# Usable methods
		"copy",
		"hash",
		"init",
		"isEqual:",
		"isProxy",
		"methodForSelector:",
		"methodSignatureForSelector:",
		"mutableCopy",
		
		# Methods for which objc provides better interfaces
		##"autorelease", # Handled by CFFI gc hook
		##"class", # obj.cls
		##"conformsToProtocol:", # isinstance(obj, protocol)
		##"debugDescription", # repr(obj)
		##"description", # repr(obj)
		##"isKindOfClass:", # isinstance(obj, cls)
		##"isMemberOfClass:", # obj.cls == cls
		##"superclass", # obj.cls.superclass
		##"release", # Handled by CFFI gc hook
		##"respondsToSelector:", # obj.responds_to(sel)
		##"retain", # Handled in __init__
		##"self", # Not necessary
		
		# Methods that aren't really useful
		##"attributeKeys",
		##"classCode",
		##"classDescription",
		##"className",
		##"copyScriptingValue:forKey:withProperties:",
		##"inverseForRelationshipKey:",
		##"newScriptingObjectOfClass:forValueForKey:withContentsValue:properties:",
		##"performSelector:",
		##"performSelector:onThread:withObject:waitUntilDone:",
		##"performSelector:onThread:withObject:waitUntilDone:modes:",
		##"performSelector:withObject:",
		##"performSelector:withObject:afterDelay:",
		##"performSelector:withObject:afterDelay:inModes:",
		##"performSelector:withObject:withObject:",
		##"performSelectorInBackground:withObject:",
		##"performSelectorOnMainThread:withObject:waitUntilDone:",
		##"performSelectorOnMainThread:withObject:waitUntilDone:modes:",
		##"retainCount",
		##"scriptingProperties",
		##"scriptingValueForSpecifier:",
		##"setScriptingProperties",
		##"toManyRelationshipKeys",
		##"toOneRelationshipKeys",
		
		# Methods that shouldn't be called directly
		##"awakeAfterUsingCoder:",
		##"classForArchiver",
		##"classForCoder",
		##"classForKeyedArchiver",
		##"classForPortCoder",
		##"dealloc",
		##"doesNotRecognizeSelector:",
		##"forwardInvocation:",
		##"forwardingTargetForSelector:",
		##"replacementObjectForArchiver:",
		##"replacementObjectForCoder:",
		##"replacementObjectForKeyedArchiver:",
		##"replacementObjectForPortCoder:",
		
		# Deprecated methods
		##"allowsWeakReference",
		##"finalize",
		##"retainWeakReference",
		##"zone",
	]),
	
	#--- NSProxy
	"NSProxy": ([
		# Usable methods
		"alloc",
		
		# Methods for which objc provides better interfaces
		##"class",
		##"respondsToSelector:",
		
		# Deprecated methods
		##"allocWithZone:",
	], [
		# Usable methods
		"hash",
		"isEqual:",
		"isProxy",
		"methodSignatureForSelector:",
		
		# Methods for which objc provides better interfaces
		##"autorelease",
		##"class",
		##"conformsToProtocol:",
		##"debugDescription",
		##"description",
		##"isKindOfClass:",
		##"isMemberOfClass:",
		##"performSelector:",
		##"performSelector:withObject:",
		##"performSelector:withObject:withObject:",
		##"release",
		##"respondsToSelector:",
		##"retain",
		##"self",
		##"superclass",
		
		# Methods that aren't really useful
		##"retainCount",
		
		# Methods that shouldn't be called directly
		##"dealloc",
		##"finalize",
		##"forwardInvocation:",
		
		# Deprecated methods
		##"zone",
	]),
	
	#--- NSSet
	"NSSet": ([
		"set",
		"setWithArray:",
		"setWithObject:",
		"setWithObjects:",
		"setWithObjects:count:",
		"setWithSet:",
	], [
		"addObserver:forKeyPath:options:context:",
		"allObjects",
		"anyObject",
		"containsObject:",
		"count",
		"countByEnumeratingWithState:objects:count:",
		"descriptionWithLocale:",
		"encodeWithCoder:",
		"enumerateObjectsUsingBlock:",
		"enumerateObjectsWithOptions:usingBlock:",
		"filteredSetUsingPredicate:",
		"initWithArray:",
		"initWithCoder:",
		"initWithObjects:",
		"initWithObjects:count:",
		"initWithSet:",
		"initWithSet:copyItems:",
		"intersectsSet:",
		"isEqualToSet:",
		"isSubsetOfSet:",
		"makeObjectsPerformSelector:",
		"makeObjectsPerformSelector:withObject:",
		"member:",
		"objectEnumerator",
		"objectsPassingTest:",
		"objectsWithOptions:passingTest:",
		"removeObserver:forKeyPath:",
		"removeObserver:forKeyPath:context:",
		"setByAddingObject:",
		"setByAddingObjectsFromArray:",
		"setByAddingObjectsFromSet:",
		"setValue:forKey:",
		"sortedArrayUsingDescriptors:",
		"valueForKey:",
	]),
	
	#--- NSString
	"NSString": ([
		# Usable methods
		"localizedNameOfStringEncoding:",
		"localizedStringWithFormat:",
		"pathWithComponents:",
		"string",
		"stringEncodingForData:encodingOptions:convertedString:usedLossyConversion:",
		"stringWithCString:encoding:",
		"stringWithCharacters:length:",
		"stringWithContentsOfFile:encoding:error:",
		"stringWithContentsOfFile:usedEncoding:error:",
		"stringWithContentsOfURL:encoding:error:",
		"stringWithContentsOfURL:usedEncoding:error:",
		"stringWithFormat:",
		"stringWithString:",
		"stringWithUTF8String:",
		
		# Deprecated methods
		##"stringWithCString:",
		##"stringWithCString:length:",
		##"stringWithContentsOfFile:",
		##"stringWithContentsOfURL:",
	], [
		# Usable methods
		"UTF8String",
		"absolutePath",
		"availableStringEncodings",
		"boolValue",
		"boundingRectWithSize:options:attributes:context:",
		"cStringUsingEncoding:",
		"canBeConvertedToEncoding:",
		"capitalizedString",
		"capitalizedStringWithLocale:",
		"caseInsensitiveCompare:",
		"characterAtIndex:",
		"commonPrefixWithString:options:",
		"compare:",
		"compare:options:",
		"compare:options:range:",
		"compare:options:range:locale:",
		"completePathIntoString:caseSensitive:matchesIntoArray:filterTypes:",
		"componentsSeparatedByCharactersInSet:",
		"componentsSeparatedByString:",
		"containsString:",
		"dataUsingEncoding:",
		"dataUsingEncoding:allowLossyConversion:",
		"decomposedStringWithCanonicalMapping",
		"decomposedStringWithCompatibilityMapping",
		"defaultCStringEncoding",
		"doubleValue",
		"drawAtPoint:withAttributes:",
		"drawInRect:withAttributes:",
		"drawWithRect:options:attributes:context:",
		"encodeWithCoder:",
		"enumerateLinesUsingBlock:",
		"enumerateLinguisticTagsInRange:scheme:options:orthography:usingBlock:",
		"enumerateSubstringsInRange:options:usingBlock:",
		"fastestEncoding",
		"fileSystemRepresentation",
		"floatValue",
		"getBytes:maxLength:usedLength:encoding:options:range:remainingRange:",
		"getCString:maxLength:encoding:",
		"getCharacters:range:",
		"getFileSystemRepresentation:maxLength:",
		"getLineStart:end:contentsEnd:forRange:",
		"getParagraphStart:end:contentsEnd:forRange:",
		"hasPrefix:",
		"hasSuffix:",
		"initWithBytes:length:encoding:",
		"initWithBytesNoCopy:length:encoding:freeWhenDone:",
		"initWithCString:encoding:",
		"initWithCharacters:length:",
		"initWithCharactersNoCopy:length:freeWhenDone:",
		"initWithCoder:",
		"initWithContentsOfFile:encoding:error:",
		"initWithContentsOfFile:usedEncoding:error:",
		"initWithContentsOfURL:encoding:error:",
		"initWithContentsOfURL:usedEncoding:error:",
		"initWithData:encoding:",
		"initWithFormat:",
		"initWithFormat:arguments:",
		"initWithFormat:locale:",
		"initWithFormat:locale:arguments:",
		"initWithString:",
		"initWithUTF8String:",
		"intValue",
		"integerValue",
		"isEqualToString:",
		"lastPathComponent",
		"length",
		"lengthOfBytesUsingEncoding:",
		"lineRangeForRange:",
		"linguisticTagsInRange:scheme:options:orthography:tokenRanges:",
		"localizedCapitalizedString",
		"localizedCaseInsensitiveCompare:",
		"localizedCaseInsensitiveContainsString:",
		"localizedCompare:",
		"localizedLowercaseString",
		"localizedStandardCompare:",
		"localizedStandardContainsString:",
		"localizedStandardRangeOfString:",
		"localizedUppercaseString",
		"longLongValue",
		"lowercaseString",
		"lowercaseStringWithLocale:",
		"maximumLengthOfBytesUsingEncoding:",
		"paragraphRangeForRange:",
		"pathComponents",
		"pathExtension",
		"precomposedStringWithCanonicalMapping",
		"precomposedStringWithCompatibilityMapping",
		"propertyList",
		"propertyListFromStringsFileFormat",
		"rangeOfCharacterFromSet:",
		"rangeOfCharacterFromSet:options:",
		"rangeOfCharacterFromSet:options:range:",
		"rangeOfComposedCharacterSequenceAtIndex:",
		"rangeOfComposedCharacterSequencesForRange:",
		"rangeOfString:",
		"rangeOfString:options:",
		"rangeOfString:options:range:",
		"rangeOfString:options:range:locale:",
		"sizeWithAttributes:",
		"smallestEncoding",
		"stringByAbbreviatingWithTildeInPath",
		"stringByAddingPercentEncodingWithAllowedCharacters:",
		"stringByAppendingFormat:",
		"stringByAppendingPathComponent:",
		"stringByAppendingPathExtension:",
		"stringByAppendingString:",
		"stringByApplyingTransform:reverse:",
		"stringByDeletingLastPathComponent",
		"stringByDeletingPathExtension",
		"stringByExpandingTildeInPath",
		"stringByFoldingWithOptions:locale:",
		"stringByPaddingToLength:withString:startingAtIndex:",
		"stringByRemovingPercentEncoding",
		"stringByReplacingCharactersInRange:withString:",
		"stringByReplacingOccurrencesOfString:withString:",
		"stringByReplacingOccurrencesOfString:withString:options:range:",
		"stringByResolvingSymlinksInPath",
		"stringByStandardizingPath",
		"stringByTrimmingCharactersInSet:",
		"stringsByAppendingPaths:",
		"substringFromIndex:",
		"substringToIndex:",
		"substringWithRange:",
		"uppercaseString",
		"uppercaseStringWithLocale:",
		"variantFittingPresentationWidth:",
		"writeToFile:atomically:encoding:error:",
		"writeToURL:atomically:encoding:error:",
		
		# Deprecated methods
		##"boundingRectWithSize:options:attributes:",
		##"cString",
		##"cStringLength",
		##"drawAtPoint:forWidth:withFont:fontSize:lineBreakMode:baselineAdjustment:",
		##"drawAtPoint:forWidth:withFont:lineBreakMode:",
		##"drawAtPoint:forWidth:withFont:minFontSize:actualFontSize:lineBreakMode:baselineAdjustment:",
		##"drawAtPoint:withFont:",
		##"drawInRect:withFont:",
		##"drawInRect:withFont:lineBreakMode:",
		##"drawInRect:withFont:lineBreakMode:alignment:",
		##"drawWithRect:options:attributes:",
		##"getCString:",
		##"getCString:maxLength:",
		##"getCString:maxLength:range:remainingRange:",
		##"getCharacters:",
		##"initWithCString:",
		##"initWithCString:length:",
		##"initWithCStringNoCopy:length:freeWhenDone:",
		##"initWithContentsOfFile:",
		##"initWithContentsOfURL:",
		##"lossyCString",
		##"sizeWithFont:",
		##"sizeWithFont:constrainedToSize:",
		##"sizeWithFont:constrainedToSize:lineBreakMode:",
		##"sizeWithFont:forWidth:lineBreakMode:",
		##"sizeWithFont:minFontSize:actualFontSize:forWidth:lineBreakMode:",
		##"stringByAddingPercentEscapesUsingEncoding:",
		##"stringByReplacingPercentEscapesUsingEncoding:",
		##"writeToFile:atomically:",
		##"writeToURL:atomically:",
	]),
	
	#--- NSValue
	"NSValue": ([
		# Usable methods
		"value:withObjCType:",
		"valueWithBytes:objCType:",
		"valueWithCATransform3D:",
		"valueWithCGAffineTransform:",
		"valueWithCGPoint:",
		"valueWithCGRect:",
		"valueWithCGSize:",
		"valueWithCGVector:",
		"valueWithCMTime:",
		"valueWithCMTimeMapping:",
		"valueWithCMTimeRange:",
		"valueWithMKCoordinate:",
		"valueWithMKCoordinateSpan:",
		"valueWithNonretainedObject:",
		"valueWithPoint:",
		"valueWithPointer:",
		"valueWithRange:",
		"valueWithRect:",
		"valueWithSize:",
		"valueWithUIEdgeInsets:",
		"valueWithUIOffset:",
		
		# Not loaded by default
		##"valueWithSCNMatrix4:",
		##"valueWithSCNVector3:",
		##"valueWithSCNVector4:",
	], [
		# Usable methods
		"encodeWithCoder:",
		"getValue:",
		"initWithBytes:objCType:",
		"initWithCoder:",
		"isEqualToValue:",
		"objCType",
		
		# Potentially unsafe
		##"CATransform3DValue",
		##"CGAffineTransformValue",
		##"CGPointValue",
		##"CGRectValue",
		##"CGSizeValue",
		##"CGVectorValue",
		##"CMTimeMappingValue",
		##"CMTimeRangeValue",
		##"CMTimeValue",
		##"MKCoordinateSpanValue",
		##"MKCoordinateValue",
		##"SCNMatrix4Value",
		##"SCNVector3Value",
		##"SCNVector4Value",
		##"UIEdgeInsetsValue",
		##"UIOffsetValue",
		##"nonretainedObjectValue",
		##"pointValue",
		##"pointerValue",
		##"rangeValue",
		##"rectValue",
		##"sizeValue",
	]),
}

